### ISSUE TITLE
Won't work with state changed?

### ISSUE THREAD

**Issue by eldyvoon** [matthewlehner/react-hmr-example#1]
I need to refresh when I changed state to see changes, why?

I open my console, I changed the state and save the file, it says nothing changed. Hmmm?

**Comment by matthewlehner** [comment]
This is the way that HMR is intended to work. A components state is intended to be changed by actions that happen within the app, so there's no way to know how you're using state, or how it's changed after the app initializes.

HMR will update the render and lifecycle functions, but intentionally does not update state because of the reasons I outlined above.
